server:
  port: 8081
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 123.56.130.207:8848
        namespace: 875a309c-4ee4-4260-9462-d8d22235068f
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/guli_pms
    username: root
    password: 123456

redis:
  host: 127.0.0.1
mybatis-plus:
  mapper-locations: classpath:mapper/pms/**/*.xml
  global-config:
    db-config:
      id-type: auto

